### ISSUE TITLE
Release 3.2 missing jvmrun and entities.xml file

### ISSUE THREAD

**Issue by scottwstevens** [hms-networks/flexy-thingworx-connector#63]
Going through the setup process today with "the latest" files/firmware and the jvm run and eitities.xml files seem to be missing from the .zip package.

**Comment by alexjhawk** [comment]
Hi @scottwstevens,

I have just released an update, Version 3.2.1, to GitHub. It includes a patch to our release script which creates the GitHub release. I have ensured that the mentioned files, as well as other required files, are now included.

Please respond back if you find that this issue is still not resolved.

V2.3.1: https://github.com/hms-networks/flexy-thingworx-connector/releases/tag/v3.2.1
